dot -T svg -o state0.svg state0.dot
dot -T svg -o state1.svg state1.dot
dot -T svg -o state2.svg state2.dot
dot -T svg -o state3.svg state3.dot
dot -T svg -o state4.svg state4.dot
dot -T svg -o state5.svg state5.dot
dot -T svg -o state6.svg state6.dot
dot -T svg -o state7.svg state7.dot
dot -T svg -o state8.svg state8.dot
dot -T svg -o state9.svg state9.dot
dot -T svg -o state10.svg state10.dot
dot -T svg -o state11.svg state11.dot
dot -T svg -o state12.svg state12.dot
dot -T svg -o state13.svg state13.dot
dot -T svg -o state14.svg state14.dot
dot -T svg -o state15.svg state15.dot
dot -T svg -o state16.svg state16.dot
dot -T svg -o state17.svg state17.dot
dot -T svg -o state18.svg state18.dot
dot -T svg -o state19.svg state19.dot
dot -T svg -o state20.svg state20.dot
dot -T svg -o state21.svg state21.dot
dot -T svg -o state22.svg state22.dot
dot -T svg -o state23.svg state23.dot
dot -T svg -o state24.svg state24.dot
dot -T svg -o state25.svg state25.dot
dot -T svg -o state26.svg state26.dot
dot -T svg -o state27.svg state27.dot
dot -T svg -o state28.svg state28.dot
dot -T svg -o state29.svg state29.dot
dot -T svg -o state30.svg state30.dot